### ISSUE TITLE
Supply comparison function

### ISSUE THREAD

**Issue by Rhobal** [smart-table/smart-table-sort#1]
Currently, the comparison function uses fixed "less than" in `return aVal < bVal ? -1 : 1;`

I would like to perform a case insensitive sort, how can I supply my own comparison function to compare aVal and bVal?

**Comment by lorenzofox3** [comment]
This is not possible and I would rather keep this module simple for now. However you can provide a custom sort factory function on the table factory. Please refer to the [documentation](https://smart-table.github.io/www/dist/table.html)

**Comment by lorenzofox3** [comment]
Actually this could be an easy/nice enhancement

**Comment by Rhobal** [comment]
What next? I assume
* add the comparator parameter in core sort.js and thus bump core version to 2.4.0
* add stSortComparator attribute to stSort directive for angular
* how to test?

**Comment by lorenzofox3** [comment]
I am not sure I want this to be included in the core especially as people can provide other sort function through the main table factory. 
I saw your request in the context of this module only and not related to smart table (and smart-table-ng). 
I'll need to think more thoroughly whether the complication added to the API worth it, especially when you can already do it (probably less conveniently I agree). Thanks anyway for the PR, I'll review it.
